name: dh_segment_torch
channels:
  - default
  - pytorch
dependencies:
  - pip=19.3.1
  - setuptools=44.0.0
  - python=3.7
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cudatoolkit=10.1
  - tensorboard=2.0.0
  - scikit-image=0.15.0
  - scikit-learn=0.22.1
  - pandas=0.25.3
  - numpy=1.18.1
  - scipy=1.3.2
  - networkx=2.4
  - pip:
      - sacred>=0.8.0
      - pretrainedmodels>=0.7.4
      - opencv-python-headless>=4.3.0
      - PyYaml>=5.3.0
      - frozendict>=1.2
      - albumentations>=0.4.5
      - shapely>=1.7.0
      - tqdm>=4.41.1
      - requests>=2.23.0
      - pytest>=5.4.2
      - git+https://github.com/dhlab-epfl/dhSegment-torch.git@master
